### ISSUE TITLE
POC MongoDB

### ISSUE THREAD

**Issue by elShailee** [elShailee/The-Act-of-Time#31]
# POC MongoDB
## Description
In general, this is the first step at fully implementing the DB.
This task involves making the smallest piece of Database possible that could fully work,
in this case - that'll be the `activeActionsExampleData`.

## Sub-Tasks:
 - [ ] Figure out the initial installation and configuration process of MongoDB at the dev's work stations.
 - [ ] Write Instructions for said installation.
 - [ ] Create a working first piece of Database, containing and delivering `activeActionsExampleData`'s data.
 - [ ] Create a script that set-up a "default-state" database at dev environment.
